export const ENGINES = [
    {
        slug: "character-generator",
        title: "AI Character Generator",
        description: "Create professional 3D, 2D, or retro characters with full DNA preservation.",
        keywords: ["character creator", "avatar maker", "pixar style characters", "game assets"]
    },
    {
        slug: "story-studio",
        title: "AI Storyboard Generator",
        description: "Design seamless 8-frame narratives for storyboards, social content, and brand storytelling.",
        keywords: ["storyboard creator", "comic generator", "narrative ai", "visual storytelling"]
    },
    {
        slug: "mix-studio",
        title: "AI Product Ad Generator",
        description: "Composite characters with real-world products for high-end professional advertisements.",
        keywords: ["product mockup", "ai advertising", "product placement", "brand ads"]
    },
    {
        slug: "icon-generator",
        title: "AI Icon & Logo Maker",
        description: "Generate minimalist, 3D, or vector icons and logos for apps and websites.",
        keywords: ["icon maker", "logo generator", "app icon creator", "vector graphics"]
    }
];

export const INDUSTRIES = [
    { slug: "saas", title: "SaaS", description: "Professional visual assets for your software-as-a-service brand." },
    { slug: "discord", title: "Discord", description: "Design unique characters and icons for your Discord server." },
    { slug: "twitch", title: "Twitch", description: "Level up your stream with custom AI-generated Twitch assets." },
    { slug: "gaming", title: "Gaming", description: "Build legendary characters and game assets for your title." },
    { slug: "real-estate", title: "Real Estate", description: "Professional branding assets for realtors and agencies." },
    { slug: "dentistry", title: "Dentistry", description: "Approachable characters and icons for healthcare brands." },
    { slug: "coffee-shops", title: "Coffee Shops", description: "Charming branding for cafes and local coffee brands." },
    { slug: "gyms", title: "Gyms & Fitness", description: "Energetic and motivating visual assets for fitness centers." },
    { slug: "e-commerce", title: "E-commerce", description: "Branded characters and product ads for your online store." },
    { slug: "youtube", title: "YouTube", description: "Iconic avatars and thumbnails for your YouTube channel." },
    { slug: "ai-startups", title: "AI Startups", description: "Futuristic assets for the next generation of AI platforms." },
    { slug: "indie-games", title: "Indie Game Devs", description: "Affordable, high-quality character sets for independent developers." },
    { slug: "solopreneurs", title: "Solopreneurs", description: "Building an army of one with consistent personal branding." },
    { slug: "e-learning", title: "E-learning", description: "Engaging educational avatars and course storyboards." },
    { slug: "cybersecurity", title: "Cybersecurity", description: "Hard-edged, technical icons and characters for security firms." },
    { slug: "blockchain", title: "Web3 & Blockchain", description: "Abstract and futuristic visuals for the crypto ecosystem." },
    { slug: "interior-design", title: "Interior Design", description: "Elegant icons and showcase visuals for design professionals." },
    { slug: "fashion", title: "Fashion", description: "Stylized characters and high-end ad mockups for apparel brands." },
    { slug: "pet-care", title: "Pet Care", description: "Friendly and approachable mascots for pet brands." },
    { slug: "travel", title: "Travel Agencies", description: "Adventurous themes and icon sets for the travel industry." },
    { slug: "music", title: "Music Production", description: "Edgy avatars and assets for artists and labels." },
    { slug: "event-planning", title: "Event Planning", description: "Vibrant and celebratory visual assets for event brands." },
    { slug: "marketing", title: "Marketing Agencies", description: "White-label quality assets for client campaigns." },
    { slug: "hr-tech", title: "HR Tech", description: "Human-centric, friendly visuals for modern workplace platforms." },
    { slug: "fintech", title: "FinTech", description: "Trustworthy and modern financial design assets." },
    { slug: "logistics", title: "Logistics", description: "Industrial and efficiency-focused iconography." }
];

export const STYLES = [
    { slug: "3d-pixar", title: "3D Pixar Style", description: "High-end 3D cinematic characters and icons with Pixar-grade quality." },
    { slug: "claymation", title: "Claymation", description: "Charming stop-motion style clay assets with rich textures." },
    { slug: "minimalist", title: "Minimalist", description: "Clean, simple, and modern designs for modern brands." },
    { slug: "vector", title: "Vector Art", description: "Scalable and clean vector-style graphics for logos and print." },
    { slug: "retro-80s", title: "Retro 80s", description: "Vibrant neon and synthwave-inspired 80s designs." },
    { slug: "cyberpunk", title: "Cyberpunk", description: "Futuristic and edgy visual styles for the digital frontier." },
    { slug: "isometric", title: "Isometric", description: "Perfectly angled isometric assets for apps and websites." },
    { slug: "flat-design", title: "Flat Design", description: "Timeless flat illustration style for versatile brand use." },
    { slug: "ghibli", title: "Ghibli Inspired", description: "Dreamy, hand-painted aesthetic inspired by legendary Japanese animation." },
    { slug: "ukiyo-e", title: "Ukiyo-e Modern", description: "Traditional Japanese woodblock style reimagined for modern brands." },
    { slug: "pixel-art", title: "Pixel Art", description: "Nostalgic 16-bit and 32-bit assets for games and apps." },
    { slug: "low-poly", title: "3D Low Poly", description: "Stylish and efficient low-polygon 3D characters." },
    { slug: "vaporwave", title: "Vaporwave Pastel", description: "Aesthetic pastel gradients and glitchy retro visuals." },
    { slug: "oil-painting", title: "Oil Painting", description: "Rich, textured digital oils for a classical fine-art feel." },
    { slug: "charcoal", title: "Charcoal Sketch", description: "Rough, expressive black and white hand-drawn aesthetics." },
    { slug: "pop-art", title: "Pop Art", description: "Bold colors and Ben-Day dots inspired by 60s comic art." },
    { slug: "glassmorphism", title: "Glassmorphism", description: "Modern frosted glass effects for high-end UI elements." },
    { slug: "neumorphism", title: "Neumorphism", description: "Soft, organic 3D-like interface elements and icons." }
];

export const LOCATIONS = [
    { slug: "new-york", name: "New York", country: "USA" },
    { slug: "london", name: "London", country: "UK" },
    { slug: "tokyo", name: "Tokyo", country: "Japan" },
    { slug: "san-francisco", name: "San Francisco", country: "USA" },
    { slug: "los-angeles", name: "Los Angeles", country: "USA" },
    { slug: "chicago", name: "Chicago", country: "USA" },
    { slug: "austin", name: "Austin", country: "USA" },
    { slug: "seattle", name: "Seattle", country: "USA" },
    { slug: "boston", name: "Boston", country: "USA" },
    { slug: "berlin", name: "Berlin", country: "Germany" },
    { slug: "paris", name: "Paris", country: "France" },
    { slug: "singapore", name: "Singapore", country: "Singapore" },
    { slug: "sydney", name: "Sydney", country: "Australia" },
    { slug: "toronto", name: "Toronto", country: "Canada" },
    { slug: "amsterdam", name: "Amsterdam", country: "Netherlands" },
    { slug: "dublin", name: "Dublin", country: "Ireland" },
    { slug: "barcelona", name: "Barcelona", country: "Spain" },
    { slug: "houston", name: "Houston", country: "USA" },
    { slug: "miami", name: "Miami", country: "USA" },
    { slug: "denver", name: "Denver", country: "USA" },
    { slug: "atlanta", name: "Atlanta", country: "USA" },
    { slug: "portland", name: "Portland", country: "USA" },
    { slug: "nashville", name: "Nashville", country: "USA" },
    { slug: "dubai", name: "Dubai", country: "UAE" },
    { slug: "seoul", name: "Seoul", country: "South Korea" },
    { slug: "mumbai", name: "Mumbai", country: "India" },
    { slug: "bangalore", name: "Bangalore", country: "India" },
    { slug: "vancouver", name: "Vancouver", country: "Canada" },
    { slug: "melbourne", name: "Melbourne", country: "Australia" },
    { slug: "stockholm", name: "Stockholm", country: "Sweden" },
    { slug: "helsinki", name: "Helsinki", country: "Finland" },
    { slug: "oslo", name: "Oslo", country: "Norway" },
    { slug: "copenhagen", name: "Copenhagen", country: "Denmark" },
    { slug: "tel-aviv", name: "Tel Aviv", country: "Israel" },
    { slug: "munich", name: "Munich", country: "Germany" },
    { slug: "madrid", name: "Madrid", country: "Spain" },
    { slug: "milan", name: "Milan", country: "Italy" },
    { slug: "mexico-city", name: "Mexico City", country: "Mexico" },
    { slug: "sao-paulo", name: "Sao Paulo", country: "Brazil" },
    { slug: "cape-town", name: "Cape Town", country: "South Africa" },
    { slug: "lisbon", name: "Lisbon", country: "Portugal" },
    { slug: "vienna", name: "Vienna", country: "Austria" },
    { slug: "warsaw", name: "Warsaw", country: "Poland" },
    { slug: "prague", name: "Prague", country: "Czech Republic" },
    { slug: "istanbul", name: "Istanbul", country: "Turkey" },
    { slug: "bangkok", name: "Bangkok", country: "Thailand" },
    { slug: "hong-kong", name: "Hong Kong", country: "China" },
    { slug: "kuala-lumpur", name: "Kuala Lumpur", country: "Malaysia" },
    { slug: "jakarta", name: "Jakarta", country: "Indonesia" },
    { slug: "manila", name: "Manila", country: "Philippines" },
    { slug: "taipei", name: "Taipei", country: "Taiwan" },
    { slug: "ho-chi-minh-city", name: "Ho Chi Minh City", country: "Vietnam" },
    { slug: "beijing", name: "Beijing", country: "China" },
    { slug: "shanghai", name: "Shanghai", country: "China" },
    { slug: "guangzhou", name: "Guangzhou", country: "China" },
    { slug: "shenzhen", name: "Shenzhen", country: "China" },
    { slug: "delhi", name: "Delhi", country: "India" },
    { slug: "chennai", name: "Chennai", country: "India" },
    { slug: "hyderabad", name: "Hyderabad", country: "India" },
    { slug: "pune", name: "Pune", country: "India" },
    { slug: "ahmedabad", name: "Ahmedabad", country: "India" },
    { slug: "karachi", name: "Karachi", country: "Pakistan" },
    { slug: "lahore", name: "Lahore", country: "Pakistan" },
    { slug: "dhaka", name: "Dhaka", country: "Bangladesh" },
    { slug: "abu-dhabi", name: "Abu Dhabi", country: "UAE" },
    { slug: "riyadh", name: "Riyadh", country: "Saudi Arabia" },
    { slug: "jeddah", name: "Jeddah", country: "Saudi Arabia" },
    { slug: "cairo", name: "Cairo", country: "Egypt" },
    { slug: "lagos", name: "Lagos", country: "Nigeria" },
    { slug: "nairobi", name: "Nairobi", country: "Kenya" },
    { slug: "johannesburg", name: "Johannesburg", country: "South Africa" },
    { slug: "casablanca", name: "Casablanca", country: "Morocco" },
    { slug: "guadalajara", name: "Guadalajara", country: "Mexico" },
    { slug: "monterrey", name: "Monterrey", country: "Mexico" },
    { slug: "rio-de-janeiro", name: "Rio de Janeiro", country: "Brazil" },
    { slug: "buenos-aires", name: "Buenos Aires", country: "Argentina" },
    { slug: "santiago", name: "Santiago", country: "Chile" },
    { slug: "bogota", name: "Bogota", country: "Colombia" },
    { slug: "lima", name: "Lima", country: "Peru" },
    { slug: "philadelphia", name: "Philadelphia", country: "USA" },
    { slug: "phoenix", name: "Phoenix", country: "USA" },
    { slug: "san-diego", name: "San Diego", country: "USA" },
    { slug: "dallas", name: "Dallas", country: "USA" },
    { slug: "san-jose", name: "San Jose", country: "USA" },
    { slug: "columbus", name: "Columbus", country: "USA" },
    { slug: "charlotte", name: "Charlotte", country: "USA" },
    { slug: "indianapolis", name: "Indianapolis", country: "USA" },
    { slug: "san-antonio", name: "San Antonio", country: "USA" },
    { slug: "jacksonville", name: "Jacksonville", country: "USA" },
    { slug: "fort-worth", name: "Fort Worth", country: "USA" },
    { slug: "detroit", name: "Detroit", country: "USA" },
    { slug: "el-paso", name: "El Paso", country: "USA" },
    { slug: "memphis", name: "Memphis", country: "USA" },
    { slug: "baltimore", name: "Baltimore", country: "USA" },
    { slug: "oklahoma-city", name: "Oklahoma City", country: "USA" },
    { slug: "las-vegas", name: "Las Vegas", country: "USA" },
    { slug: "louisville", name: "Louisville", country: "USA" },
    { slug: "milwaukee", name: "Milwaukee", country: "USA" },
    { slug: "albuquerque", name: "Albuquerque", country: "USA" },
    { slug: "tucson", name: "Tucson", country: "USA" },
    { slug: "fresno", name: "Fresno", country: "USA" },
    { slug: "sacramento", name: "Sacramento", country: "USA" },
    { slug: "long-beach", name: "Long Beach", country: "USA" },
    { slug: "kansas-city", name: "Kansas City", country: "USA" },
    { slug: "mesa", name: "Mesa", country: "USA" },
    { slug: "virginia-beach", name: "Virginia Beach", country: "USA" },
    { slug: "colorado-springs", name: "Colorado Springs", country: "USA" },
    { slug: "raleigh", name: "Raleigh", country: "USA" },
    { slug: "omaha", name: "Omaha", country: "USA" },
    { slug: "oakland", name: "Oakland", country: "USA" },
    { slug: "tulsa", name: "Tulsa", country: "USA" },
    { slug: "minneapolis", name: "Minneapolis", country: "USA" },
    { slug: "cleveland", name: "Cleveland", country: "USA" },
    { slug: "wichita", name: "Wichita", country: "USA" },
    { slug: "arlington", name: "Arlington", country: "USA" },
    { slug: "new-orleans", name: "New Orleans", country: "USA" },
    { slug: "bakersfield", name: "Bakersfield", country: "USA" },
    { slug: "tampa", name: "Tampa", country: "USA" },
    { slug: "honolulu", name: "Honolulu", country: "USA" },
    { slug: "aurora", name: "Aurora", country: "USA" },
    { slug: "anaheim", name: "Anaheim", country: "USA" },
    { slug: "santa-ana", name: "Santa Ana", country: "USA" },
    { slug: "st-louis", name: "St. Louis", country: "USA" },
    { slug: "riverside", name: "Riverside", country: "USA" },
    { slug: "corpus-christi", name: "Corpus Christi", country: "USA" },
    { slug: "lexington", name: "Lexington", country: "USA" },
    { slug: "pittsburgh", name: "Pittsburgh", country: "USA" },
    { slug: "anchorage", name: "Anchorage", country: "USA" },
    { slug: "stockton", name: "Stockton", country: "USA" },
    { slug: "cincinnati", name: "Cincinnati", country: "USA" },
    { slug: "st-paul", name: "St. Paul", country: "USA" },
    { slug: "greensboro", name: "Greensboro", country: "USA" },
    { slug: "toledo", name: "Toledo", country: "USA" },
    { slug: "newark", name: "Newark", country: "USA" },
    { slug: "plano", name: "Plano", country: "USA" },
    { slug: "henderson", name: "Henderson", country: "USA" },
    { slug: "lincoln", name: "Lincoln", country: "USA" },
    { slug: "orlando", name: "Orlando", country: "USA" },
    { slug: "jersey-city", name: "Jersey City", country: "USA" },
    { slug: "chula-vista", name: "Chula Vista", country: "USA" },
    { slug: "buffalo", name: "Buffalo", country: "USA" },
    { slug: "fort-wayne", name: "Fort Wayne", country: "USA" },
    { slug: "chandler", name: "Chandler", country: "USA" },
    { slug: "st-petersburg", name: "St. Petersburg", country: "USA" },
    { slug: "laredo", name: "Laredo", country: "USA" },
    { slug: "madison", name: "Madison", country: "USA" },
    { slug: "durham", name: "Durham", country: "USA" },
    { slug: "lubbock", name: "Lubbock", country: "USA" },
    { slug: "scottsdale", name: "Scottsdale", country: "USA" },
    { slug: "reno", name: "Reno", country: "USA" },
    { slug: "glendale", name: "Glendale", country: "USA" },
    { slug: "norfolk", name: "Norfolk", country: "USA" },
    { slug: "winston-salem", name: "Winston-Salem", country: "USA" },
    { slug: "north-las-vegas", name: "North Las Vegas", country: "USA" },
    { slug: "irving", name: "Irving", country: "USA" },
    { slug: "chesapeake", name: "Chesapeake", country: "USA" },
    { slug: "gilbert", name: "Gilbert", country: "USA" },
    { slug: "hialeah", name: "Hialeah", country: "USA" },
    { slug: "garland", name: "Garland", country: "USA" },
    { slug: "fremont", name: "Fremont", country: "USA" },
    { slug: "baton-rouge", name: "Baton Rouge", country: "USA" },
    { slug: "richmond", name: "Richmond", country: "USA" },
    { slug: "boise", name: "Boise", country: "USA" },
    { slug: "san-bernardino", name: "San Bernardino", country: "USA" },
];

export const COMPETITORS = [
    { slug: "midjourney", name: "Midjourney", type: "AI Image Generator", strength: "Artistic expression", weakness: "Consistency and UI" },
    { slug: "dalle", name: "DALL-E 3", type: "AI Image Generator", strength: "Instruction following", weakness: "Photorealism" },
    { slug: "canva", name: "Canva", type: "Design Platform", strength: "Ease of use", weakness: "Generic templates" },
    { slug: "leonardo-ai", name: "Leonardo.ai", type: "AI Creative Suite", strength: "Fine-tuned models", weakness: "Complexity" },
    { slug: "adobe-firefly", name: "Adobe Firefly", type: "Enterprise AI", strength: "Integration with Creative Cloud", weakness: "Commercial restrictions" },
];

export function getSEOContent(category?: string, location?: string) {
    const catText = category ? category.toLowerCase() : "professional brand assets";

    const tips: string[] = [];
    if (category?.includes("Mascot") || category?.includes("Character")) {
        tips.push("Focus on eye contact and facial expressions to build an emotional connection with your audience.");
        tips.push("Ensure your character remains consistent across different poses for recognizable brand DNA.");
    }
    if (category?.includes("Icon") || category?.includes("Logo")) {
        tips.push("Simplify details so your icon remains legible even at small sizes like 16x16 pixels.");
        tips.push("Use bold, contrasting colors to help your app stand out on crowded home screens.");
    }
    if (category?.includes("Story")) {
        tips.push("Maintain color palette and character features across all 8 frames for a cinematic feel.");
    }

    if (tips.length === 0) {
        tips.push("Leverage AI to test multiple style variations before committing to a final brand guide.");
        tips.push("Export your assets in high-resolution formats to ensure clarity across all digital platforms.");
    }

    return {
        intro: `Generate world-class ${catText} in seconds. Our AI-powered studio is calibrated for professional designers who need identity consistency and cinematic quality${location ? ` in ${location}` : ""}.`,
        benefit1: `For ${location || "modern brands"}, our identity-lock technology prevents character drift, ensuring your mascot looks perfect every time.`,
        benefit2: `Achieve studio-grade results without the studio-grade cost. Ideal for ${location ? `${location}-based startups` : "high-growth companies"} looking to scale their visual production.`,
        tips
    };
}
